### ISSUE TITLE
rgw: generate random API key and token on first run

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/s3gw-core#15]
Instead of relying on the hard coded user id, api key, and token, have them being generated when the database is first created, and outputted to the user. We can also, alternatively, write down a json file directly with those values onto the rgw data directory (which might be better than outputting credentials to the log.)

**Comment by trociny** [comment]
Probably it would be better if instead of generating random keys it could get them as input params, e.g. from environment variables. I guess it will be easier for an "orchestrator" to work this way.

Also, creating a user on db initialization is a temporary hack, which I suppose will be removed when `radosgw-admin` supports the db backend.

And actually I think the idea to create the backend db automatically was bad, and I would rather it is removed from the rgw eventually and instead `mkfs` like command is provided to initialize the backend manually (similarly to `ceph-osd --mkfs` we currently have). Otherwise it will be difficult for users to detect errors when the db volume is not mounted or the db path is incorrectly specified, and the radosgw instead of fail will just silently create a new db in a wrong location.

So, instead of working on how to pass user data on automatic user creation (or get them back if the credentials generated randomly), we could start working on `radosgw --mkfs` command. And  the command could optionally get user credentials if we want a user to be created.

**Comment by trociny** [comment]
As a workaround we could just update the user directly in the db, like below:
```
echo 'UPDATE default_ns_user_table SET AccessKeysID = "0555b35654ad1656d804", AccessKeysSecret = "h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==" WHERE UserID = "testid";' | sqlite3 default_ns.db
```
In my tests it even did not require the rgw restart to apply the changes. It looks like the rgw does not cache the user in memory and read from db on every request? Which would probably be not very optimal.

It might be useful for our orchestrator/setup scripts unless a better solution is provided.
