### ISSUE TITLE
Look into using BCI instead of Tumbleweed

### ISSUE THREAD

**Issue by jhmarina** [aquarist-labs/s3gw-core#19]

**Comment by votdev** [comment]
Tried to use `registry.suse.com/bci/bci-base:latest` but there are many problems with missing packages, e.g. `libthrift-devel` is only available in Tumbleweed with the required package version.

**Comment by votdev** [comment]
According to the [registry information](https://registry.opensuse.org/cgi-bin/cooverview?srch_term=project%3D%5EopenSUSE%3AContainers%3A+container%3Dtumbleweed) the Tumbleweed image is about 38 MB. I've discussed with @jecluis that we will not continue our efforts to switch to a BCI image because the Tumbleweed is also very small and building Ceph is much easier in Tumbleweed than using SLE15SP3.
