### ISSUE TITLE
UI: Ingress must allow client's http header reaching backend untouched 

### ISSUE THREAD

**Issue by jhmarina** [aquarist-labs/s3gw-core#45]
[When trying to set up the explorer ](
https://github.com/aquarist-labs/s3gw-core/pull/40) tool there were issues related to CORS.

In order to be able to deliver a UI both for user management and the explorer, we need to sort these issues out.

[UPDATE]
This item is about Ingress behavior, not about CORS.

**Comment by giubacc** [comment]
I have done an analysis on the problem and I found that this is not related with CORS.
The issue is related with the Ingress and how we are authenticating with radosgw. 
S3 authentication method is based on a HMAC signature computed using a secret_key over a bunch of http's header fields.
Because the client send also an access_key inside the header, this can be used by the server to compute the signature over the same header fields and ultimately check if the client and the server produce the same signature.
If the server produces the same client's signature, the request is authenticated and it is served.
There is more than a signature version that can be used with S3 protocol: v1, v2, v3 and v4.
v4 in particular, uses also the `host` in the set of fields used to compose the string to sign.
This means that, the value of the `host` in the http's header must be exactly the same used by the client when reaching the backend.
If the Ingress, for example, manipulates this field and the client is using a signature v4, the request will be rejected because the signature computed by the backend will mismatch.
Both NGINX and Traefik ingresses modify `host` field.
With NGINX this behavior can be changed and make it pass exactly the same value set by the client.
With Traefik this probably is possible, but from my research, this seems much more complicated and not properly documented.
My feeling here is that NGINX is completely customizable in these aspects and that it is much more documented.
The Explorer GUI is using a v4 signature, I try to set a v2 version, but it seems to me that is still sending requests with v4 format.
So, currently, we are able to make the browser working only with NGINX, because we know how to manipulate an http's header.
As side note,  `s3cmd` is working with Traefik because the configuration is set to use a v2 signature and thus, the host is not involved in the signature.
I try NGINX with k3s and with that the browser is working (bad, but it works).

What do you think @jecluis , @votdev , @jhmarina , @0xavi0  ?
Should we consider the idea of dropping Traefik and try to support NGINX only? 
Or should we try to support both?

**Comment by giubacc** [comment]
Update:

1) 

https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

At this link is explained that v4 will be the only supported auth method for new aws regions.
I think it is reasonable try to go in this direction and support v4 method with s3gw.

2)

I searched for methods to manipulate the header with Traefik, the official documentation suggest to use `header` middelware:

https://doc.traefik.io/traefik/middlewares/http/headers/

specifically: `customRequestHeaders`.

Searched online and also downloaded the Treafik repo, but it seems that the only thing you can do with this middleware is to set a _static_ value for a header field.
We would need something that allow to copy the original `Host` value into the forwarded one.
