### ISSUE TITLE
radosgw dbstore: db file size does not decrease after removing object

### ISSUE THREAD

**Issue by trociny** [aquarist-labs/s3gw-core#6]
The size of the db file (default_ns.db) does not decrease after removing objects.

I.e. if I just run in a loop `put` and `rm` commands for the same object the default_ns.db is constantly growing.

**Comment by jecluis** [comment]
Funny enough we are getting a crash when `rm` an object (#7). What version were you running when this happened?

**Comment by trociny** [comment]
I was trying it on the master

**Comment by giubacc** [comment]
dbstore uses 2 tables in order to persist an object:

```
default_ns_test_object_table
default_ns_test_objectdata_table
```
If the object being persisted is less than a certain size then it will store it inline on the first table only.
If the object is more than a certain size dbstore will paginate the content on the second table using potentially more than 1 row.
The buggy scenario is the second one: removing an object will cause the record being removed from the `object` table but not in the `objectdata` table.
This is causing `objectdata` table to grow indefinitely.
